---
- name: install packages
  with_items: "{{ mlmmj_packages }}"
  pkgng:
    name: "{{ item.name }}"

- name: create mlmmj user
  user:
    name: mlmmj

- name: create lists directory
  file:
    path: /usr/home/mlmmj/lists
    state: directory
    mode: 0750

- name: install mlmmj list create script
  copy:
    src: new-mlmmj-list.sh
    dest: /usr/local/bin/new-mlmmj-list.sh
    mode: 0755

- name: create transport for postfix
  file:
    path: /usr/local/etc/postfix/transport
    state: touch
    mode: 0644
  notify:
    - refresh transport
    - restart postfix
