---
- name: install packages
  with_items: "{{ mlmmj_packages }}"
  pkgng:
    name: "{{ item.name }}"

- name: create mlmmj user
  user:
    name: mlmmj

- name: create lists directory
  file:
    path: /usr/home/mlmmj/lists
    state: directory
    mode: 0750
    owner: mlmmj
    group: mlmmj

- name: create archive directory
  file:
    path: /usr/home/mlmmj/webarchive
    state: directory
    mode: 0755
    owner: mlmmj
    group: mlmmj

- name: install mlmmj list create script
  copy:
    src: new-mlmmj-list.sh
    dest: /usr/local/bin/new-mlmmj-list.sh
    mode: 0755

- name: install mlmmj helper script
  copy:
    src: mlmmj-helper
    dest: /usr/local/bin/mlmmj-helper
    mode: 0755
