---
- name: install packages
  with_items: "{{ postfix_packages }}"
  pkgng:
    name: "{{ item.name }}"

- name: confgure postfix service
  template:
    src: postfix.j2
    dest: /etc/rc.conf.d/postfix
    owner: root
    group: wheel

- name: create cert dir
  file:
    path: /usr/local/etc/postfix/certs
    owner: root
    group: wheel
    state: directory

- name: configure postfix
  with_items: "{{ postfix_templates }}"
  copy:
    src: "{{ item.filename }}.tpl"
    dest: "{{ item.destination }}/{{ item.filename }}"
