---
dovecot_packages:
  - name: dovecot
  - name: dovecot-pigeonhole

dovecot_templates:
  - destination: /usr/local/etc/dovecot
    filename: dovecot.conf

  - destination: /usr/local/etc/dovecot
    filename: dovecot-ldap.conf.ext

  - destination: /usr/local/etc/dovecot/conf.d
    filename: 10-auth.conf

  - destination: /usr/local/etc/dovecot/conf.d
    filename: 10-master.conf

  - destination: /usr/local/etc/dovecot/conf.d
    filename: 10-mail.conf

  - destination: /usr/local/etc/dovecot/conf.d
    filename: 10-ssl.conf

  - destination: /usr/local/etc/dovecot/conf.d
    filename: 15-lda.conf

  - destination: /usr/local/etc/dovecot/conf.d
    filename: 20-lmtp.conf

  - destination: /usr/local/etc/dovecot/conf.d
    filename: 20-managesieve.conf

  - destination: /usr/local/etc/dovecot/conf.d
    filename: 90-sieve.conf

  - destination: /usr/local/etc/dovecot/conf.d
    filename: auth-ldap.conf.ext
