---
dovecot_packages:
  - name: dovecot
  - name: dovecot-pigeonhole

dovecot_templates:
  - src: dovecot.conf
    dest: ""

  - src: dovecot-ldap.conf.ext
    dest: ""

  - src: 10-auth.conf
    dest: conf.d

  - src: 10-mail.conf
    dest: conf.d

  - src: 10-master.conf
    dest: conf.d

  - src: 10-ssl.conf
    dest: conf.d

  - src: auth-ldap.conf.ext
    dest: conf.d
